services:
  vacationsystemdb:
    container_name: vacationsystemdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - mssql_vacationsystem:/var/opt/mssql
